# Generated by Django 4.2.5 on 2023-09-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_resident', to='api.resident'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_apartment', to='api.apartment'),
        ),
    ]
